[app]
app_name = "boruscraper"
log_level = "INFO"

[modules]
enabled = ["boruscraper"]
paths = ["src.apps.experemental"]

[boruscraper]
save_path = "downloads"
deduplication_threshold = 10
db_path = "data.db"
