"""LLM Module messages: Commands and Events."""
from __future__ import annotations

from src.core.messages import Command, Event


class ProcessTextCommand(Command):
    """Command to process text through the NLP pipeline and then an LLM."""
    text: str
    prompt_template: str | None = None
    use_nlp: bool = True


class TextProcessedEvent(Event):
    """Event emitted when text has been processed by the NLP pipeline."""
    original_text: str
    processed_text: str
    tokens: list[str]


class GenerateResponseCommand(Command):
    """Command to generate a response from the LLM."""
    prompt: str


class ResponseGeneratedEvent(Event):
    """Event emitted when a response has been generated by the LLM."""
    prompt: str
    response: str
