[system]
name = "ImageDedup"
version = "0.1.0"

[modules]
vfs = { path = "src.modules.vfs.module.VfsModule" }
imagededup = { path = "src.apps.ImageDedup.module.ImageDedupModule" }

[vfs]
url = "osfs://"
root_path = "."
