[app]
app_name = "ImageAnalyze"
log_level = "DEBUG"

[ui]
current_skin = "arctic_frost"

[modules]
paths = ["src.apps", "src.modules"]
enabled = ["ImageAnalyze"]

[presets."Max 2000"]
rules = [
    { cond_type = "AreaCondition", cond_vars = { min_area = 4000000 }, act_type = "ScaleAction", act_vars = { max_width = 2000, max_height = 2000 } }
]

[presets."To WebP"]
rules = [
    { cond_type = "FormatCondition", cond_vars = { target_formats = [".webp"], invert = true }, act_type = "ConvertAction", act_vars = { target_format = ".webp", quality = 90, delete_original = true } }
]

[presets."Cleanup Tiny"]
rules = [
    { cond_type = "SizeCondition", cond_vars = { max_bytes = 1024 }, act_type = "DeleteAction", act_vars = {} },
    { cond_type = "AreaCondition", cond_vars = { max_area = 4096 }, act_type = "DeleteAction", act_vars = {} }
]
